services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - MYSQL_HOST=db
        - MYSQL_PORT=3306
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_DATABASE=ticketing_system
        - GO_ENV=production
        - TZ=Asia/Jakarta
    ports:
        - "10002:10001"
        - "8081:8081"
    depends_on:
      - db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  liquibase:
    build:
        context: .
        dockerfile: liquibase/Dockerfile
    depends_on:
      - db
#    volumes:
#      - ./liquibase/ticketing-system/sql:/liquibase/changelog
  db:
    image: mysql:8.0.23
    platform: linux/amd64
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql
      - ./mysql-files:/var/lib/mysql-files
    restart: always
    environment:
      MYSQL_DATABASE: 'ticketing_system'
      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'root'
      # You can use whatever password you like
#      MYSQL_PASSWORD: 'root123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - "3308:3306"
volumes:
  .:
  logvolume01: {}
